# Reference Source Code Manager
#
# Clone external libraries here for easy reference during development.
# These are NOT dependencies - just for reading source/examples.
#
# Usage:
#   task clone:all    # Clone all reference repos
#   task clone:via    # Clone specific repo
#   task update:all   # Pull latest for all repos
#   task clean        # Remove all cloned repos

version: "3"

tasks:
  default:
    desc: List available repos
    cmds:
      - echo "Reference repos (clone to .src/ for reading source code):"
      - echo ""
      - echo "  via                - Via web framework"
      - echo "  via-plugin-picocss - Via PicoCSS plugin"
      - echo "  browser            - gost-dom headless browser"
      - echo "  process-compose    - Process orchestrator"
      - echo "  nats-server        - NATS server"
      - echo "  narun              - NATS micro services"
      - echo "  conf               - Ardanlabs config"
      - echo "  vals               - Secret store values"
      - echo ""
      - echo "Commands:"
      - echo "  task clone:all     - Clone all repos"
      - echo "  task clone:<name>  - Clone specific repo"
      - echo "  task update:all    - Pull latest for all"
      - echo "  task clean         - Remove all cloned repos"
    silent: true

  clone:all:
    desc: Clone all reference repos
    cmds:
      - task: clone:via
      - task: clone:via-plugin-picocss
      - task: clone:browser
      - task: clone:process-compose
      - task: clone:nats-server
      - task: clone:narun
      - task: clone:conf
      - task: clone:vals

  clone:via:
    desc: Clone Via web framework
    cmds:
      - git clone https://github.com/go-via/via.git via 2>/dev/null || echo "via already exists"
    status:
      - test -d via

  clone:via-plugin-picocss:
    desc: Clone Via PicoCSS plugin
    cmds:
      - git clone https://github.com/go-via/via-plugin-picocss.git via-plugin-picocss 2>/dev/null || echo "via-plugin-picocss already exists"
    status:
      - test -d via-plugin-picocss

  clone:browser:
    desc: Clone gost-dom browser
    cmds:
      - git clone https://github.com/gost-dom/browser.git browser 2>/dev/null || echo "browser already exists"
    status:
      - test -d browser

  clone:process-compose:
    desc: Clone process-compose
    cmds:
      - git clone https://github.com/F1bonacc1/process-compose.git process-compose 2>/dev/null || echo "process-compose already exists"
    status:
      - test -d process-compose

  clone:nats-server:
    desc: Clone NATS server
    cmds:
      - git clone https://github.com/nats-io/nats-server.git nats-server 2>/dev/null || echo "nats-server already exists"
    status:
      - test -d nats-server

  clone:narun:
    desc: Clone narun (NATS micro services)
    cmds:
      - git clone https://github.com/akhenakh/narun.git narun 2>/dev/null || echo "narun already exists"
    status:
      - test -d narun

  clone:conf:
    desc: Clone Ardanlabs conf
    cmds:
      - git clone https://github.com/ardanlabs/conf.git conf 2>/dev/null || echo "conf already exists"
    status:
      - test -d conf

  clone:vals:
    desc: Clone helmfile vals
    cmds:
      - git clone https://github.com/helmfile/vals.git vals 2>/dev/null || echo "vals already exists"
    status:
      - test -d vals

  update:all:
    desc: Pull latest for all cloned repos
    cmds:
      - for dir in */; do echo "Updating $dir..."; (cd "$dir" && git pull --ff-only 2>/dev/null || true); done

  clean:
    desc: Remove all cloned repos
    prompt: This will delete all cloned reference repos. Continue?
    cmds:
      - rm -rf via via-plugin-picocss browser process-compose nats-server narun conf vals
      - echo "All reference repos removed"
