version: '3'

# Taskfile for via-nats web dashboard
#
# This dashboard provides web-based auth lifecycle management for nats-node
#
# Usage:
#   task        # List all tasks
#   task run    # Start the Via dashboard
#   task dev    # Start with auto-reload (if air installed)

vars:
  VIA_PORT: '{{default "3001" .VIA_PORT}}'

tasks:
  default:
    cmds:
      - task --list-all

  run:
    desc: Run the Via dashboard
    env:
      VIA_PORT: '{{.VIA_PORT}}'
      GOWORK: 'off'
    cmds:
      - go run .

  build:
    desc: Build the Via dashboard binary
    env:
      GOWORK: 'off'
    cmds:
      - go build -o via-nats .

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  # Quick access to nats-node tasks
  mesh:
    desc: Start the nats-node mesh
    dir: ../nats-node
    cmds:
      - task mesh

  mesh:down:
    desc: Stop the nats-node mesh
    dir: ../nats-node
    cmds:
      - task mesh:down

  auth:status:
    desc: Show current auth mode
    dir: ../nats-node
    cmds:
      - task auth:status

  # Cleanup shortcuts
  clean:
    desc: Remove nats-node data directories
    dir: ../nats-node
    cmds:
      - task clean

  clean:logs:
    desc: Remove nats-node log files
    dir: ../nats-node
    cmds:
      - task clean:logs

  clean:all:
    desc: Remove all data, logs, and auth (full reset)
    dir: ../nats-node
    cmds:
      - task clean:all

  clean:via:
    desc: Remove via-nats binary
    cmds:
      - rm -f via-nats
